### ISSUE TITLE
Make sure errors are displayed via the JSON API if there are any

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/iron-starter-api#1]
https://github.com/learn-co-curriculum/iron-starter-api/blob/fe0b9f991113e55da229649735d6c4e93eedffe8/app/controllers/api/campaigns_controller.rb#L17

It will make debugging for the students *much easier*

**Comment by jmburges** [comment]
this is true for all actions in both controllers

**Comment by jmburges** [comment]
Or since you are using `!` methods remind themin the labs to look at their terminal

**Comment by Lukeghenco** [comment]
@joe this is handled with an ExceptionHandler which, I'm going to go over in another lesson to avoid a ton of repeat logic https://github.com/learn-co-curriculum/iron-starter-api/blob/master/app/controllers/concerns/exception_handler.rb.

**Comment by jmburges** [comment]
coolcool
